services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus_server.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus-agent:
    image: prom/prometheus:latest
    container_name: prometheus-agent
    volumes:
      - ./prometheus_agent.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
    command:
      - "--enable-feature=agent"
      - "--config.file=/etc/prometheus/prometheus.yml"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  go-app1:
    build: ./go-app1
    container_name: go-app1
    ports:
      - "8081:8080"

  go-app2:
    build: ./go-app2
    container_name: go-app2
    ports:
      - "8082:8080"

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-app1
      - go-app2
