global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'go-app1'
    static_configs:
      - targets: ['go-app1:8080']

  - job_name: 'go-app2'
    static_configs:
      - targets: ['go-app2:8080']

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
