global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: prom2

scrape_configs:
  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'sidecar2'
    static_configs:
      - targets: ['sidecar2:19092']
