global:
  scrape_interval: 2s

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf-aggregator:9273']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["go-app1:8080", "go-app2:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
  - job_name: 'json_exporter'
    metrics_path: /probe
    params:
      module: [default]
    static_configs:
      - targets: [ "http://go-json:8080" ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: json_exporter:7979
